In [2]:
my_list=[1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [6]:
arr=np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
import numpy as np

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.93814268, 0.41623042, 0.73033561, 0.16491436, 0.52267331])

In [25]:
np.random.rand(5,5)

array([[0.55957388, 0.06987375, 0.79958366, 0.64314767, 0.60110533],
       [0.16318289, 0.49531801, 0.90148837, 0.42666612, 0.06739932],
       [0.90249672, 0.92144346, 0.73795794, 0.45174366, 0.17164054],
       [0.15461182, 0.7813325 , 0.19948101, 0.46654688, 0.54103439],
       [0.25170914, 0.40843169, 0.13531811, 0.66399029, 0.09021738]])

In [27]:
np.random.randint(1,100)

21

In [28]:
np.random.randint(1,100)

11

In [29]:
np.random.randint(1,100)

86

In [30]:
np.random.randint(1,100)

98

In [31]:
np.random.randint(1,100)

53

In [32]:
np.random.randint(1,10,4)

array([7, 5, 3, 6])

In [34]:
arr= np.arange(25)
ranarr = np.random.randint(0,50,10)

In [35]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr

array([29, 32, 23, 18, 48, 22, 32, 28, 31, 35])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ranarr


array([29, 32, 23, 18, 48, 22, 32, 28, 31, 35])

In [40]:
ranarr.max()

48

In [41]:
ranarr.argmax()

4

In [42]:
ranarr.min()

18

In [43]:
ranarr.argmin()

3

In [44]:
arr.shape

(25,)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.shape

(25,)

In [47]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [49]:
arr.reshape(25,1).shape

(25, 1)

In [50]:
arr.dtype

dtype('int32')