In [2]:
import numpy as np


In [4]:
arr= np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [10]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])