In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

In [4]:
from sklearn.model_selection import train_test_split, cross_val_score 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
#4 Feature Scaling.
from sklearn.preprocessing import StandardScaler


In [8]:
sc = StandardScaler()

In [10]:
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
X_test

array([[3.00e+01, 8.70e+04],
       [3.80e+01, 5.00e+04],
       [3.50e+01, 7.50e+04],
       [3.00e+01, 7.90e+04],
       [3.50e+01, 5.00e+04],
       [2.70e+01, 2.00e+04],
       [3.10e+01, 1.50e+04],
       [3.60e+01, 1.44e+05],
       [1.80e+01, 6.80e+04],
       [4.70e+01, 4.30e+04],
       [3.00e+01, 4.90e+04],
       [2.80e+01, 5.50e+04],
       [3.70e+01, 5.50e+04],
       [3.90e+01, 7.70e+04],
       [2.00e+01, 8.60e+04],
       [3.20e+01, 1.17e+05],
       [3.70e+01, 7.70e+04],
       [1.90e+01, 8.50e+04],
       [5.50e+01, 1.30e+05],
       [3.50e+01, 2.20e+04],
       [3.50e+01, 4.70e+04],
       [4.70e+01, 1.44e+05],
       [4.10e+01, 5.10e+04],
       [4.70e+01, 1.05e+05],
       [2.30e+01, 2.80e+04],
       [4.90e+01, 1.41e+05],
       [2.80e+01, 8.70e+04],
       [2.90e+01, 8.00e+04],
       [3.70e+01, 6.20e+04],
       [3.20e+01, 8.60e+04],
       [2.10e+01, 8.80e+04],
       [3.70e+01, 7.90e+04],
       [5.70e+01, 6.00e+04],
       [3.70e+01, 5.30e+04],
       [2.40e+

In [12]:
X_train

array([[ 0.58164944, -0.88670699],
       [-0.60673761,  1.46173768],
       [-0.01254409, -0.5677824 ],
       [-0.60673761,  1.89663484],
       [ 1.37390747, -1.40858358],
       [ 1.47293972,  0.99784738],
       [ 0.08648817, -0.79972756],
       [-0.01254409, -0.24885782],
       [-0.21060859, -0.5677824 ],
       [-0.21060859, -0.19087153],
       [-0.30964085, -1.29261101],
       [-0.30964085, -0.5677824 ],
       [ 0.38358493,  0.09905991],
       [ 0.8787462 , -0.59677555],
       [ 2.06713324, -1.17663843],
       [ 1.07681071, -0.13288524],
       [ 0.68068169,  1.78066227],
       [-0.70576986,  0.56295021],
       [ 0.77971394,  0.35999821],
       [ 0.8787462 , -0.53878926],
       [-1.20093113, -1.58254245],
       [ 2.1661655 ,  0.93986109],
       [-0.01254409,  1.22979253],
       [ 0.18552042,  1.08482681],
       [ 0.38358493, -0.48080297],
       [-0.30964085, -0.30684411],
       [ 0.97777845, -0.8287207 ],
       [ 0.97777845,  1.8676417 ],
       [-0.01254409,

In [13]:
X_test=sc.fit_transform(X_test)

In [14]:
X_test

array([[-0.54748976,  0.5130727 ],
       [ 0.15442019, -0.61825566],
       [-0.10879604,  0.14615539],
       [-0.54748976,  0.26846116],
       [-0.10879604, -0.61825566],
       [-0.81070599, -1.53554892],
       [-0.45975102, -1.68843113],
       [-0.0210573 ,  2.25592989],
       [-1.60035469, -0.0678797 ],
       [ 0.94406888, -0.83229075],
       [-0.54748976, -0.6488321 ],
       [-0.72296725, -0.46537345],
       [ 0.06668145, -0.46537345],
       [ 0.24215893,  0.20730828],
       [-1.4248772 ,  0.48249625],
       [-0.37201227,  1.43036596],
       [ 0.06668145,  0.20730828],
       [-1.51261594,  0.45191981],
       [ 1.64597884,  1.8278597 ],
       [-0.10879604, -1.47439603],
       [-0.10879604, -0.70998498],
       [ 0.94406888,  2.25592989],
       [ 0.41763642, -0.58767922],
       [ 0.94406888,  1.06344865],
       [-1.16166097, -1.29093738],
       [ 1.11954637,  2.16420057],
       [-0.72296725,  0.5130727 ],
       [-0.63522851,  0.2990376 ],
       [ 0.06668145,

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0) 

In [20]:
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test) 

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [23]:
cm

array([[61,  7],
       [ 3, 29]], dtype=int64)

In [24]:
from sklearn.metrics import accuracy_score

In [28]:
score=accuracy_score(y_test,y_pred)

In [29]:
score

0.9

In [34]:
classifier.score(X_test,y_test)

0.9

In [35]:
classifier.score(X_train,y_train)

1.0