In [16]:
import torch
import numpy as np

In [2]:
x = torch.empty(2,3, 4)
x

tensor([[[8.4490e-39, 1.1112e-38, 9.5511e-39, 1.0102e-38],
         [7.3470e-39, 1.0653e-38, 1.0194e-38, 4.6838e-39],
         [8.4489e-39, 9.6429e-39, 9.2755e-39, 1.0286e-38]],

        [[9.0919e-39, 8.9082e-39, 9.2755e-39, 8.4490e-39],
         [1.0194e-38, 9.0919e-39, 8.4490e-39, 9.9184e-39],
         [9.0000e-39, 9.0919e-39, 4.2246e-39, 1.1112e-38]]])

In [3]:
x = torch.rand(2,2)
print(x)
print(x.dtype)

tensor([[0.6721, 0.6651],
        [0.8298, 0.8887]])
torch.float32


In [7]:
x = torch.ones(2,2, dtype=torch.int64)
print(x)
print(x.dtype)

tensor([[1, 1],
        [1, 1]])
torch.int64


In [8]:
x = torch.tensor([2.5,0.1])
print(x)
print(x.dtype)

tensor([2.5000, 0.1000])
torch.float32


In [9]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = torch.add(x,y)
z

tensor([[1.3130, 1.1778],
        [1.5405, 1.4953]])

In [10]:
x = torch.rand(2,2)
y = torch.rand(2,2)
y.add_(x)   # y = y + x
y

tensor([[0.8640, 1.2844],
        [1.1275, 1.2356]])

In [14]:
x = torch.rand(4,3)
print(x)
print(x[:,0])
print(x[1,:])
print(x[0,0].item())

tensor([[0.7335, 0.5820, 0.4576],
        [0.3279, 0.9718, 0.9179],
        [0.7677, 0.6710, 0.3814],
        [0.8428, 0.4322, 0.2669]])
tensor([0.7335, 0.3279, 0.7677, 0.8428])
tensor([0.3279, 0.9718, 0.9179])
0.7335076928138733


In [15]:
x = torch.rand(4,3)
print(x)
y = x.view(12)
print(y)

tensor([[0.5018, 0.9094, 0.7445],
        [0.9980, 0.2722, 0.8111],
        [0.3963, 0.9424, 0.8448],
        [0.7355, 0.3558, 0.7508]])
tensor([0.5018, 0.9094, 0.7445, 0.9980, 0.2722, 0.8111, 0.3963, 0.9424, 0.8448,
        0.7355, 0.3558, 0.7508])


In [17]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


In [21]:
a.add_(1)
print(b)

[3. 3. 3. 3. 3.]


In [22]:
c = torch.from_numpy(b)
print(c)

tensor([3., 3., 3., 3., 3.])


In [24]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to("cpu")
    print(z)

tensor([2., 2., 2., 2., 2.])


In [25]:
x = torch.ones(5, requires_grad=True)   # x requires grad
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
