In [1]:
import torch
import numpy as np

In [2]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-1.2754,  0.6118, -1.5135], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([0.7246, 2.6118, 0.4865], grad_fn=<AddBackward0>)


In [4]:
z = y*y*2
print(z)

tensor([ 1.0502, 13.6435,  0.4733], grad_fn=<MulBackward0>)


In [5]:
z = z.mean()
print(z)

z.backward()    # backpropagation to calculate gradients
print(x.grad)   # gradients

tensor(5.0557, grad_fn=<MeanBackward0>)
tensor([0.9662, 3.4825, 0.6486])


In [7]:
x.requires_grad_(False) # turn off gradients for x

tensor([-1.2754,  0.6118, -1.5135])

In [8]:
x = torch.randn(3, requires_grad=True)
x.detach() # detach from graph, so that it is no longer a part of the computation graph

tensor([ 1.3822,  0.3675, -0.2959])

In [9]:
with torch.no_grad():
    x = torch.randn(3, requires_grad=True)
    y = x * 2
    print(y)

tensor([-0.3846,  1.0687,  0.2157])


In [12]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()  # sum of weights * 3

    model_output.backward() # backpropagation

    print(weights.grad)

    weights.grad.zero_()    # zero the gradient

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
