# LOGISTIC REGRESSION

### Iris flower Classification

In [1]:
## importing all the necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import random

## Binary Classification

In [2]:
def sigmoid(X):
    
    Y = 1 / (1 + np.exp(-X))
    
    return Y    

In [3]:
x_temp = np.random.rand(5,6)
y_temp = sigmoid(x_temp)
print(x_temp)
print(y_temp)

[[0.03976526 0.2139404  0.38265868 0.28064247 0.58292526 0.40552943]
 [0.23193619 0.71946807 0.25837453 0.35892819 0.74299501 0.09888583]
 [0.68021095 0.87529062 0.93804178 0.80487551 0.90841527 0.81599868]
 [0.67218767 0.78680819 0.75940483 0.81848939 0.22046572 0.47369603]
 [0.92464499 0.66093219 0.31102984 0.7310941  0.09821365 0.23441834]]
[[0.50994001 0.55328203 0.59451418 0.56970373 0.64174023 0.60001544]
 [0.5577255  0.67248987 0.56423667 0.58878095 0.67765043 0.52470133]
 [0.66378578 0.70584537 0.71870394 0.69101643 0.71267577 0.69338631]
 [0.66199284 0.68714558 0.6812245  0.69391559 0.55489427 0.61625818]
 [0.71598761 0.65946976 0.57713661 0.67504532 0.52453369 0.55833768]]


## Cost function

In [4]:
def cost_fun(y,h):
    
    cost = -1/y.size * np.sum( np.dot(y.T,np.log(h)) + np.dot(1-y.T, np.log(1-h)))
    
    return cost

In [5]:
def gradient(X):
    
    X = sigmoid(X)*(1-sigmoid(X))
    
    return X    

In [6]:
x_temp = np.random.rand(5,6)

y_temp = [1.,0.,1.,1.,0.]
y_temp = np.array(y_temp)
y_temp = np.expand_dims(y_temp,axis = 1)

w_temp = np.random.rand(x_temp.shape[1],1)

y_hat = sigmoid(np.dot(x_temp,w_temp))

cost = cost_fun(y_temp,y_hat)
print("cost : {}".format(cost))

g = gradient(np.dot(x_temp,w_temp))
print(f"gradient : {g}")

cost : 1.0721461211938885
gradient : [[0.09753063]
 [0.0505594 ]
 [0.09780491]
 [0.07103742]
 [0.10575785]]


## loading a datasets of iris flower classification

In [7]:
iris_data = pd.read_csv(r"IRIS.csv")
iris_data.head(10)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

### storeing the data set in a array from tabular form

In [8]:
iris_data = np.array(iris_data)
print(iris_data.shape)
print(iris_data)

(150, 5)
[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [4.6 3.4 1.4 0.3 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [4.4 2.9 1.4 0.2 'Iris-setosa']
 [4.9 3.1 1.5 0.1 'Iris-setosa']
 [5.4 3.7 1.5 0.2 'Iris-setosa']
 [4.8 3.4 1.6 0.2 'Iris-setosa']
 [4.8 3.0 1.4 0.1 'Iris-setosa']
 [4.3 3.0 1.1 0.1 'Iris-setosa']
 [5.8 4.0 1.2 0.2 'Iris-setosa']
 [5.7 4.4 1.5 0.4 'Iris-setosa']
 [5.4 3.9 1.3 0.4 'Iris-setosa']
 [5.1 3.5 1.4 0.3 'Iris-setosa']
 [5.7 3.8 1.7 0.3 'Iris-setosa']
 [5.1 3.8 1.5 0.3 'Iris-setosa']
 [5.4 3.4 1.7 0.2 'Iris-setosa']
 [5.1 3.7 1.5 0.4 'Iris-setosa']
 [4.6 3.6 1.0 0.2 'Iris-setosa']
 [5.1 3.3 1.7 0.5 'Iris-setosa']
 [4.8 3.4 1.9 0.2 'Iris-setosa']
 [5.0 3.0 1.6 0.2 'Iris-setosa']
 [5.0 3.4 1.6 0.4 'Iris-setosa']
 [5.2 3.5 1.5 0.2 'Iris-setosa']
 [5.2 3.4 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.6 0.2 'Iris-setosa']
 

**y stores the data values of 4th column and x stores the other 4 parameters.**

In [9]:
y = iris_data[:,4]
print(len(y))
print(y)

150
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versic

In [10]:
x=np.array(iris_data[:,:4],dtype=float) # Or x=np.array(iris_data[:,0:4],dtype=float)
print(len(x))
print(x)

150
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.

### Feature Scaling

In [11]:
temp_mean= np.mean(x,axis=0)      #the mean value of x
x = x-temp_mean

print(x) 

[[-7.43333333e-01  4.46000000e-01 -2.35866667e+00 -9.98666667e-01]
 [-9.43333333e-01 -5.40000000e-02 -2.35866667e+00 -9.98666667e-01]
 [-1.14333333e+00  1.46000000e-01 -2.45866667e+00 -9.98666667e-01]
 [-1.24333333e+00  4.60000000e-02 -2.25866667e+00 -9.98666667e-01]
 [-8.43333333e-01  5.46000000e-01 -2.35866667e+00 -9.98666667e-01]
 [-4.43333333e-01  8.46000000e-01 -2.05866667e+00 -7.98666667e-01]
 [-1.24333333e+00  3.46000000e-01 -2.35866667e+00 -8.98666667e-01]
 [-8.43333333e-01  3.46000000e-01 -2.25866667e+00 -9.98666667e-01]
 [-1.44333333e+00 -1.54000000e-01 -2.35866667e+00 -9.98666667e-01]
 [-9.43333333e-01  4.60000000e-02 -2.25866667e+00 -1.09866667e+00]
 [-4.43333333e-01  6.46000000e-01 -2.25866667e+00 -9.98666667e-01]
 [-1.04333333e+00  3.46000000e-01 -2.15866667e+00 -9.98666667e-01]
 [-1.04333333e+00 -5.40000000e-02 -2.35866667e+00 -1.09866667e+00]
 [-1.54333333e+00 -5.40000000e-02 -2.65866667e+00 -1.09866667e+00]
 [-4.33333333e-02  9.46000000e-01 -2.55866667e+00 -9.98666667e

### Spliting the datasets into 80% train set and 20% test set

In [12]:
train = random.sample(range(0,150),120)
print(len(train))
print(train)

120
[87, 57, 135, 1, 34, 16, 101, 83, 137, 130, 51, 115, 142, 91, 103, 118, 19, 141, 140, 49, 122, 15, 126, 123, 95, 62, 53, 26, 12, 3, 100, 108, 24, 138, 67, 46, 59, 92, 66, 124, 102, 31, 28, 111, 45, 80, 18, 77, 47, 117, 133, 63, 0, 139, 132, 14, 134, 131, 11, 39, 119, 43, 70, 35, 114, 64, 145, 6, 106, 76, 72, 44, 86, 74, 129, 144, 4, 54, 52, 127, 149, 136, 148, 96, 113, 93, 85, 50, 121, 112, 105, 8, 37, 110, 89, 42, 10, 71, 30, 99, 27, 32, 147, 55, 94, 20, 48, 104, 7, 5, 88, 41, 33, 107, 68, 25, 73, 65, 13, 79]


In [13]:
validation = [i for i in range (150) if not (i in train)]
print(len(validation))
print(validation)

30
[2, 9, 17, 21, 22, 23, 29, 36, 38, 40, 56, 58, 60, 61, 69, 75, 78, 81, 82, 84, 90, 97, 98, 109, 116, 120, 125, 128, 143, 146]


#### Here x_train is our input training data and y_train is our output training data

In [14]:
x_train=(x[train,:4])
print(x_train.shape)
print (x_train)

(120, 4)
[[ 4.56666667e-01 -7.54000000e-01  6.41333333e-01  1.01333333e-01]
 [-9.43333333e-01 -6.54000000e-01 -4.58666667e-01 -1.98666667e-01]
 [ 1.85666667e+00 -5.40000000e-02  2.34133333e+00  1.10133333e+00]
 [-9.43333333e-01 -5.40000000e-02 -2.35866667e+00 -9.98666667e-01]
 [-9.43333333e-01  4.60000000e-02 -2.25866667e+00 -1.09866667e+00]
 [-4.43333333e-01  8.46000000e-01 -2.45866667e+00 -7.98666667e-01]
 [-4.33333333e-02 -3.54000000e-01  1.34133333e+00  7.01333333e-01]
 [ 1.56666667e-01 -3.54000000e-01  1.34133333e+00  4.01333333e-01]
 [ 5.56666667e-01  4.60000000e-02  1.74133333e+00  6.01333333e-01]
 [ 1.55666667e+00 -2.54000000e-01  2.34133333e+00  7.01333333e-01]
 [ 5.56666667e-01  1.46000000e-01  7.41333333e-01  3.01333333e-01]
 [ 5.56666667e-01  1.46000000e-01  1.54133333e+00  1.10133333e+00]
 [-4.33333333e-02 -3.54000000e-01  1.34133333e+00  7.01333333e-01]
 [ 2.56666667e-01 -5.40000000e-02  8.41333333e-01  2.01333333e-01]
 [ 4.56666667e-01 -1.54000000e-01  1.84133333e+00  6.

### Now we added a column of 1 in the x_train array 

In [15]:
x_train = np.concatenate((x_train,np.ones((120,1),dtype=float)),axis=1)
print(x_train.shape)

(120, 5)


### Now we defined a array y_train of 120*3 whose each every element is 0 and it will define the output 
### If one data is of first class of 3 then it will make the first element of that row 1 , similarly for 2nd class second element of the row becomes 1 and for last class 3rd element of the row of y_train will become 1.

In [16]:
y_train = np.zeros((120,3)) 
print(y_train)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0.

In [17]:
for i,j in zip(train,range(120)):
    if y[i]=='Iris-setosa':
        y_train[j,0]=1                 # for iris_data in setosa make 1 in y_train
    if y[i]=='Iris-versicolor':
        y_train[j,1]=1                 # for iris_data in versicolor make 1 in y_train
    if y[i]=='Iris-virginica':
        y_train[j,2]=1                 # for iris_data in virginica make 1 in y_train
print(y_train)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0.

### Similarly we will proceed for the validation dataset

In [18]:
x_test =(x[validation,:4])
x_test = np.concatenate((x_test,np.ones((30,1))),axis=1)
print(x_test)

[[-1.14333333e+00  1.46000000e-01 -2.45866667e+00 -9.98666667e-01
   1.00000000e+00]
 [-9.43333333e-01  4.60000000e-02 -2.25866667e+00 -1.09866667e+00
   1.00000000e+00]
 [-7.43333333e-01  4.46000000e-01 -2.35866667e+00 -8.98666667e-01
   1.00000000e+00]
 [-7.43333333e-01  6.46000000e-01 -2.25866667e+00 -7.98666667e-01
   1.00000000e+00]
 [-1.24333333e+00  5.46000000e-01 -2.75866667e+00 -9.98666667e-01
   1.00000000e+00]
 [-7.43333333e-01  2.46000000e-01 -2.05866667e+00 -6.98666667e-01
   1.00000000e+00]
 [-1.14333333e+00  1.46000000e-01 -2.15866667e+00 -9.98666667e-01
   1.00000000e+00]
 [-3.43333333e-01  4.46000000e-01 -2.45866667e+00 -9.98666667e-01
   1.00000000e+00]
 [-1.44333333e+00 -5.40000000e-02 -2.45866667e+00 -9.98666667e-01
   1.00000000e+00]
 [-8.43333333e-01  4.46000000e-01 -2.45866667e+00 -8.98666667e-01
   1.00000000e+00]
 [ 4.56666667e-01  2.46000000e-01  9.41333333e-01  4.01333333e-01
   1.00000000e+00]
 [ 7.56666667e-01 -1.54000000e-01  8.41333333e-01  1.01333333e-01

In [19]:
y_test = np.zeros((30,3))
print(y_test)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Simialrly we change the y_test array as per given data in the dataset

In [20]:
for i,j in zip(validation,range(120)):
    if y[i]=='Iris-setosa':
        y_test[j,0]=1             # for iris_data in setosa make 1 in y_train
    if y[i]=='Iris-versicolor':
        y_test[j,1]=1             # for iris_data in vericolor make 1 in y_train
    if y[i]=='Iris-virginica':
        y_test[j,2]=1             # for iris_data in virginica make 1 in y_train
print(y_test)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


## Gradient descent 
### Now we will define theta a 5*3 matrix which will give gradient for each parameter  for each class

Weight matrix for logistice regression will have shape = (no_of_features + 1, no_of_classes)

In [21]:
def initialize_parameters(x,classes):
    
    n = x.shape[1]
    theta = np.random.rand(n, classes)*0.01
    
    return theta

In [22]:
def predict_prob(x, theta):
    
    h = sigmoid(np.dot(x,theta))
    
    return h

In [23]:
def accuracy(h, y):
    
    m = y.shape[0]
    h = np.argmax(h,axis=1)                          # max value in each row of h array of sigmoid function
    q = np.argmax(y,axis=1) == h                     # check how many output we got correct
    print(np.sum(q*100/m))
    

## Model

In [24]:
def model(x, y, classes = 3, learning_rate = 1, iterations = 1000):
    
    m = x.shape[0]
    theta = initialize_parameters(x, classes)
    
    for i in range (iterations):
        h = predict_prob(x, theta)                          # sigmoid function update
        theta -= ((learning_rate)/m)*(np.dot((h-y).T , x).T)    # theta update
    
    accuracy(h,y)
    
    return theta

In [25]:
theta = model(x_train, y_train, learning_rate = 3, iterations = 5000)
theta

96.66666666666667


array([[  0.36559371,  -0.12728254,  -2.44976641],
       [  3.9090293 ,  -2.61883156,  -4.97912021],
       [ -5.8049886 ,   1.12745913,   7.95669333],
       [ -2.30917546,  -2.47779736,  14.04087279],
       [ -6.16434421,  -1.10686071, -15.92921529]])

### Now we will test our test data set and see the accuracy 

In [26]:
h = predict_prob(x_test, theta)
accuracy(h, y_test)

99.99999999999997
