In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2)


In [27]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

d:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9583333333333334

In [28]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9805555555555555

In [29]:
rf=RandomForestClassifier(n_estimators=50)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9694444444444444

In [30]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [31]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)
    

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [35]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [37]:
print(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

0.9722222222222222


In [46]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
lr_score=[]
rf_score=[]
svm_score=[]
for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    svm_score.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    rf_score.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))
    lr_score.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))

d:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
d:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_

In [45]:
svm_score

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [48]:
lr_score

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [49]:
rf_score

[0.9348914858096828, 0.9565943238731218, 0.9265442404006677]

In [51]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(), digits.data,digits.target,cv=3)

array([0.93989983, 0.95158598, 0.92487479])

In [55]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(), digits.data,digits.target,cv=3).mean()

0.9699499165275459

In [54]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), digits.data,digits.target,cv=3).mean()

d:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
d:\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_

0.9265442404006677